# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EcAQ7sec1LEwfABd-yF2_dNJa7cPDLuj
"""

!pip install -q diffusers transformers accelerate torch pillow controlnet_aux

import torch
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel
from controlnet_aux import CannyDetector
from PIL import Image
import matplotlib.pyplot as plt
from google.colab import files

print("Loading Gen AI Model...")


device = "cuda" if torch.cuda.is_available() else "cpu"

controlnet = ControlNetModel.from_pretrained(
    "lllyasviel/control_v11p_sd15_canny",
    torch_dtype=torch.float16
)

pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet,
    torch_dtype=torch.float16,
    safety_checker=None
).to(device)

canny = CannyDetector()
print(" Model loaded!")
print("\nUpload your image:")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]
image = Image.open(image_path).convert("RGB").resize((512, 512))
edge_image = canny(image)
print("\n🎨 Generating sketch...")
sketch = pipe(
    prompt="pencil sketch, detailed drawing, black and white",
    negative_prompt="color, ugly, blurry",
    image=edge_image,
    num_inference_steps=20
).images[0]
fig, axes = plt.subplots(1, 2, figsize=(12, 6))
axes[0].imshow(image)
axes[0].set_title('Original')
axes[0].axis('off')
axes[1].imshow(sketch)
axes[1].set_title('AI Sketch')
axes[1].axis('off')
plt.show()

# Save and download
sketch.save('sketch.png')
files.download('sketch.png')
print(" Done!")